<?php

namespace atc\Bkkp\Modules\Employment\Fields;

use WXC\Core\Contracts\FieldGroupInterface;
use WXC\Core\Contracts\SubtypeFieldGroupInterface;
use WXC\Core\SubtypeRegistrar;

final class EmployersGroupFields implements FieldGroupInterface, SubtypeFieldGroupInterface
{
    public function getPostType(): string
    {
        return 'group';
    }

    public function getSubtypeSlug(): string
    {
        return 'employers';
    }

    public static function register(): void
    {
        //error_log( '=== EmployersGroupFields: register()) ===' );
        if ( ! function_exists( 'acf_add_local_field_group' ) ) {
            return;
        }

        //$tax = SubtypeRegistrar::getTaxonomyForPostType( 'group' ); // rex_group_type
        $taxonomy = "group_category";

        //use atc\WHx4\Migrations\FieldKeyMigrator;
        /*
        // Migrate
        FieldKeyMigrator::migrate([
            'field_624775f4b6221' => [
                'new_field_key' => 'field_whx4_modulename_first_name',
                'old_meta_key'  => 'first_name',
                'new_meta_key'  => 'whx4_modulename_first_name',
            ],
            'field_abc123xyz456' => [
                'new_field_key' => 'field_whx4_notes',
                // no meta_key rename
            ],
        ]);
        */

        acf_add_local_field_group( array(
            'key' => 'group_5febac8aa90d9',
            'title' => 'Employer/Employment Details',
            'fields' => array(
                array(
                    'key' => 'field_66282d177de51',
                    'label' => 'Employer Overview',
                    'name' => '',
                    'aria-label' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'placement' => 'top',
                    'endpoint' => 0,
                    'selected' => 0,
                ),
                array(
                    'key' => 'field_642c54ab016bc',
                    'label' => 'Employer TIN',
                    'name' => 'employer_tin',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '15',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'maxlength' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                ),
                array(
                    'key' => 'field_62a11beef3564',
                    'label' => 'Employment Classification',
                    'name' => 'employment_classification',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '15',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'maxlength' => '',
                    'placeholder' => '1099-NEC', // TODO: change to select? W2, 1099-NEC...
                    'prepend' => '',
                    'append' => '',
                ),
                array(
                    'key' => 'field_642869a88ac6e',
                    'label' => 'Employment Activities (WIP)',
                    'name' => 'employment_activities',
                    'aria-label' => '',
                    'type' => 'checkbox',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '30',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => array(
                        'singing' => 'Singing',
                        'acting' => 'Acting',
                        'geekwork' => 'IT',
                        'other' => 'Other',
                    ),
                    'default_value' => array(
                    ),
                    'return_format' => 'value',
                    'allow_custom' => 0,
                    'layout' => 'horizontal',
                    'toggle' => 0,
                    'save_custom' => 0,
                    'custom_choice_button_text' => 'Add new choice',
                ),
                array(
                    'key' => 'field_62a11c3ff3568',
                    'label' => 'Contracted (P/P/F) (TMP)',
                    'name' => 'contracted_ppf',
                    'aria-label' => '',
                    'type' => 'true_false',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '15',
                        'class' => '',
                        'id' => '',
                    ),
                    'message' => '',
                    'default_value' => 0,
                    'ui' => 0,
                    'ui_on_text' => '',
                    'ui_off_text' => '',
                ),
                array(
                    'key' => 'field_62a11bcdf3560',
                    'label' => 'Work Location (TMP)',
                    'name' => 'work_location_tmp',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '15',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'maxlength' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                ),
                array(
                    'key' => 'field_62a11be4f3563',
                    'label' => 'IRS Form TMP',
                    'name' => 'irs_form',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '15',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'maxlength' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                ),
                array(
                    'key' => 'field_62a11c26f3567',
                    'label' => 'Work Category (TMP)',
                    'name' => 'work_category_tmp',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '20',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'maxlength' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                ),
                array(
                    'key' => 'field_66282cf27de50',
                    'label' => 'Employment History',
                    'name' => '',
                    'aria-label' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'placement' => 'top',
                    'endpoint' => 0,
                    'selected' => 0,
                ),
                array(
                    'key' => 'field_62a11bfbf3565',
                    'label' => 'Year of First Employ. (TMP)',
                    'name' => 'start_year',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '15',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'maxlength' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                ),
                array(
                    'key' => 'field_62a11c16f3566',
                    'label' => 'Dates of Employment (TMP)',
                    'name' => 'dates_of_employment',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'maxlength' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                ),
                array(
                    'key' => 'field_65ca45618209e',
                    'label' => 'Years of Employment',
                    'name' => 'years_of_employment',
                    'aria-label' => '',
                    'type' => 'checkbox',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => array(
                        1990 => '1990',
                        1991 => '1991',
                        1992 => '1992',
                        1993 => '1993',
                        1994 => '1994',
                        1995 => '1995',
                        1996 => '1996',
                        1997 => '1997',
                        1998 => '1998',
                        1999 => '1999',
                        2000 => '2000',
                        2001 => '2001',
                        2002 => '2002',
                        2003 => '2003',
                        2004 => '2004',
                        2005 => '2005',
                        2006 => '2006',
                        2007 => '2007',
                        2008 => '2008',
                        2009 => '2009',
                        2010 => '2010',
                        2011 => '2011',
                        2012 => '2012',
                        2013 => '2013',
                        2014 => '2014',
                        2015 => '2015',
                        2016 => '2016',
                        2017 => '2017',
                        2018 => '2018',
                        2019 => '2019',
                        2020 => '2020',
                        2021 => '2021',
                        2022 => '2022',
                        2023 => '2023',
                        2024 => '2024',
                        2025 => '2025',
                        2026 => '2026',
                        2027 => '2027',
                        2028 => '2028',
                        2029 => '2029',
                        2030 => '2030',
                        2031 => '2031',
                        2032 => '2032',
                        2033 => '2033',
                        2034 => '2034',
                        2035 => '2035',
                        2036 => '2036',
                        2037 => '2037',
                        2038 => '2038',
                        2039 => '2039',
                        2040 => '2040',
                    ),
                    'default_value' => array(
                    ),
                    'return_format' => 'value',
                    'allow_custom' => 0,
                    'layout' => 'horizontal',
                    'toggle' => 0,
                    'save_custom' => 0,
                    'custom_choice_button_text' => 'Add new choice',
                ),
                array(
                    'key' => 'field_5febac946eb8c',
                    'label' => 'Yearly Income',
                    'name' => 'yearly_income',
                    'aria-label' => '',
                    'type' => 'repeater',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'formula' => '',
                    'calculated_format' => '',
                    'blank_if_zero' => 0,
                    'collapsed' => '',
                    'min' => 0,
                    'max' => 0,
                    'layout' => 'table',
                    'button_label' => 'Add Row',
                    'rows_per_page' => 20,
                    'sub_fields' => array(
                        array(
                            'key' => 'field_642713548fb40',
                            'label' => 'Year (NUM)',
                            'name' => 'year_num',
                            'aria-label' => '',
                            'type' => 'number',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '10',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'min' => '',
                            'max' => '',
                            'placeholder' => '',
                            'step' => '',
                            'prepend' => '',
                            'append' => '',
                            'parent_repeater' => 'field_5febac946eb8c',
                        ),
                        array(
                            'key' => 'field_5febacdb6eb8e',
                            'label' => 'Income',
                            'name' => 'income',
                            'aria-label' => '',
                            'type' => 'number',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'formula' => '',
                            'calculated_format' => '',
                            'blank_if_zero' => 0,
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'min' => '',
                            'max' => '',
                            'step' => '',
                            'parent_repeater' => 'field_5febac946eb8c',
                        ),
                    ),
                ),
            ),
            'location' => array(
                array(
                    array(
                        'param' => 'post_type',
                        'operator' => '==',
                        'value' => 'group',
                    ),
                    array(
                        'param' => 'post_taxonomy',
                        'operator' => '==',
                        'value' => 'group_category:employers',
                    ),
                ),
                array(
                    array(
                        'param' => 'post_type',
                        'operator' => '==',
                        'value' => 'person',
                    ),
                    array(
                        'param' => 'post_taxonomy',
                        'operator' => '==',
                        'value' => 'person_category:employers',
                    ),
                ),
            ),
            'menu_order' => 0,
            'position' => 'acf_after_title',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => '',
            'active' => true,
            'description' => '',
            'show_in_rest' => 0,
        ) );
    }
}
