<?php

namespace atc\Bkkp\Modules\Employment\Fields;

use atc\WXC\Contracts\FieldGroupInterface;
use atc\WXC\Contracts\SubtypeFieldGroupInterface;
use atc\WXC\PostTypes\SubtypeRegistrar;

final class WorkPaymentDocumentFields implements FieldGroupInterface, SubtypeFieldGroupInterface
{
    public function getPostType(): string
    {
        return 'document';
    }

    public function getSubtypeSlug(): string
    {
        return 'workpayments';
    }

    public static function register(): void
    {
        if ( ! function_exists( 'acf_add_local_field_group' ) ) {
            return;
        }

        //$tax = SubtypeRegistrar::getTaxonomyForPostType( 'group' ); // rex_group_type
        $taxonomy = "document_category";

        /*acf_add_local_field_group( [
            'key'    => 'field_rex_employment_group_fields',
            'title'  => 'Employment (Employer Details)',
            'fields' => [
                [
                    'key'   => 'field_rex_employment_industry',
                    'name'  => 'rex_employment_industry',
                    'label' => 'Industry',
                    'type'  => 'text',
                ],
                // …
            ],
        ] );*/

        // Paycheck Details
        acf_add_local_field_group( array(
            'key' => 'group_62a12fd8df61c',
            'title' => 'Paycheck Details',
            'fields' => array(
                array(
                    'key' => 'field_62a1348898b99',
                    'label' => 'Basics',
                    'name' => '',
                    'aria-label' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'formula' => '',
                    'calculated_format' => '',
                    'blank_if_zero' => 0,
                    'placement' => 'top',
                    'endpoint' => 0,
                    'selected' => 0,
                ),
                array(
                    'key' => 'field_62a12fe2801f7',
                    'label' => 'Employer (Paycheck Details)',
                    'name' => 'employer',
                    'aria-label' => '',
                    'type' => 'post_object',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '20',
                        'class' => '',
                        'id' => '',
                    ),
                    'post_type' => array(
                        0 => 'group',
                    ),
                    'post_status' => '',
                    'taxonomy' => '',
                    'return_format' => 'id',
                    'multiple' => 0,
                    'allow_null' => 0,
                    'bidirectional' => 0,
                    'ui' => 1,
                    'bidirectional_target' => array(
                    ),
                ),
                array(
                    'key' => 'field_65e7311453eba',
                    'label' => 'Related Transaction',
                    'name' => 'transactions_paychecks',
                    'aria-label' => '',
                    'type' => 'post_object',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '35',
                        'class' => '',
                        'id' => '',
                    ),
                    'post_type' => array(
                        0 => 'transaction',
                    ),
                    'post_status' => '',
                    'taxonomy' => '',
                    'return_format' => 'id',
                    'multiple' => 0,
                    'allow_null' => 0,
                    'bidirectional' => 0,
                    'ui' => 1,
                    'bidirectional_target' => array(
                    ),
                ),
                array(
                    'key' => 'field_62a1304d801f8',
                    'label' => 'Pay Date',
                    'name' => 'pay_date',
                    'aria-label' => '',
                    'type' => 'date_picker',
                    'instructions' => 'AKA Check Date',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '15',
                        'class' => '',
                        'id' => '',
                    ),
                    'display_format' => 'm/d/Y',
                    'return_format' => 'm/d/Y',
                    'first_day' => 1,
                    'default_to_current_date' => 0,
                ),
                array(
                    'key' => 'field_62a1305c801f9',
                    'label' => 'Start Date',
                    'name' => 'start_date',
                    'aria-label' => '',
                    'type' => 'date_picker',
                    'instructions' => '"Period Beginning" on ADP earnings statements',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '15',
                        'class' => '',
                        'id' => '',
                    ),
                    'display_format' => 'm/d/Y',
                    'return_format' => 'm/d/Y',
                    'first_day' => 1,
                    'default_to_current_date' => 0,
                ),
                array(
                    'key' => 'field_62a13064801fa',
                    'label' => 'End Date',
                    'name' => 'end_date',
                    'aria-label' => '',
                    'type' => 'date_picker',
                    'instructions' => '"Period Ending" on ADP earnings statements',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '15',
                        'class' => '',
                        'id' => '',
                    ),
                    'display_format' => 'm/d/Y',
                    'return_format' => 'm/d/Y',
                    'first_day' => 1,
                    'default_to_current_date' => 0,
                ),
                array(
                    'key' => 'field_62a130cf801fd',
                    'label' => 'Worklog Total Due',
                    'name' => 'worklog_total_due',
                    'aria-label' => '',
                    'type' => 'number',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '20',
                        'class' => '',
                        'id' => '',
                    ),
                    'formula' => '',
                    'calculated_format' => '',
                    'blank_if_zero' => 0,
                    'readonly' => 1,
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '$',
                    'append' => '',
                    'min' => '',
                    'max' => '',
                    'step' => '',
                ),
                array(
                    'key' => 'field_62a130dd801fe',
                    'label' => 'Gross Pay',
                    'name' => 'gross_pay',
                    'aria-label' => '',
                    'type' => 'number',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '20',
                        'class' => '',
                        'id' => '',
                    ),
                    'formula' => '',
                    'calculated_format' => '',
                    'blank_if_zero' => 0,
                    'readonly' => 0,
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '$',
                    'append' => '',
                    'min' => '',
                    'max' => '',
                    'step' => '',
                ),
                array(
                    'key' => 'field_62a130ed801ff',
                    'label' => 'Net Pay',
                    'name' => 'net_pay',
                    'aria-label' => '',
                    'type' => 'number',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '20',
                        'class' => '',
                        'id' => '',
                    ),
                    'formula' => '',
                    'calculated_format' => '',
                    'blank_if_zero' => 0,
                    'readonly' => 0,
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '$',
                    'append' => '',
                    'min' => '',
                    'max' => '',
                    'step' => '',
                ),
                array(
                    'key' => 'field_62a130f880200',
                    'label' => 'Check No.',
                    'name' => 'check_num',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '20',
                        'class' => '',
                        'id' => '',
                    ),
                    'formula' => '',
                    'calculated_format' => '',
                    'blank_if_zero' => 0,
                    'readonly' => 0,
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
                array(
                    'key' => 'field_62a1310380201',
                    'label' => 'Direct Deposit?',
                    'name' => 'direct_deposit',
                    'aria-label' => '',
                    'type' => 'true_false',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '20',
                        'class' => '',
                        'id' => '',
                    ),
                    'formula' => '',
                    'calculated_format' => '',
                    'blank_if_zero' => 0,
                    'readonly' => 0,
                    'message' => '',
                    'default_value' => 0,
                    'ui' => 0,
                    'ui_on_text' => '',
                    'ui_off_text' => '',
                ),
                array(
                    'key' => 'field_62a13426ef3bb',
                    'label' => 'Worklog',
                    'name' => '',
                    'aria-label' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'formula' => '',
                    'calculated_format' => '',
                    'blank_if_zero' => 0,
                    'placement' => 'top',
                    'endpoint' => 0,
                    'selected' => 0,
                ),
                array(
                    'key' => 'field_62a1308c801fb',
                    'label' => 'Worklog v1',
                    'name' => 'worklog',
                    'aria-label' => '',
                    'type' => 'relationship',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'formula' => '',
                    'calculated_format' => '',
                    'blank_if_zero' => 0,
                    'post_type' => array(
                        0 => 'event',
                    ),
                    'taxonomy' => '',
                    'filters' => array(
                        0 => 'search',
                        1 => 'taxonomy',
                    ),
                    'elements' => '',
                    'min' => '',
                    'max' => '',
                    'return_format' => 'object',
                    'bidirectional_target' => array(
                    ),
                ),
                array(
                    'key' => 'field_62a130b7801fc',
                    'label' => 'Worklog v2 (bi)',
                    'name' => 'events_paychecks',
                    'aria-label' => '',
                    'type' => 'relationship',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'formula' => '',
                    'calculated_format' => '',
                    'blank_if_zero' => 0,
                    'post_type' => array(
                        0 => 'event',
                    ),
                    'taxonomy' => '',
                    'filters' => array(
                        0 => 'search',
                        1 => 'taxonomy',
                    ),
                    'elements' => '',
                    'min' => '',
                    'max' => '',
                    'return_format' => 'object',
                    'bidirectional_target' => array(
                    ),
                ),
                array(
                    'key' => 'field_62a13465ef3bd',
                    'label' => 'Notes',
                    'name' => '',
                    'aria-label' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'formula' => '',
                    'calculated_format' => '',
                    'blank_if_zero' => 0,
                    'placement' => 'top',
                    'endpoint' => 0,
                    'selected' => 0,
                ),
                array(
                    'key' => 'field_62a1310e80202',
                    'label' => 'Notes',
                    'name' => 'notes',
                    'aria-label' => '',
                    'type' => 'textarea',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'formula' => '',
                    'calculated_format' => '',
                    'blank_if_zero' => 0,
                    'default_value' => '',
                    'placeholder' => '',
                    'maxlength' => '',
                    'rows' => '',
                    'new_lines' => '',
                ),
            ),
            'location' => [
                [
                    [
                        'param'    => 'post_type',
                        'operator' => '==',
                        'value'    => 'document',
                    ],
                    [
                        'param'    => 'post_taxonomy',
                        'operator' => '==',
                        'value' => 'document_category:work-payments',
                    ],
                ],
                [
                    [
                        'param'    => 'post_type',
                        'operator' => '==',
                        'value'    => 'document',
                    ],
                    [
                        'param'    => 'post_taxonomy',
                        'operator' => '==',
                        'value' => 'document_category:earnings-statements',
                    ],
                ],
            ],
            'menu_order' => 0,
            'position' => 'normal',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'field',
            'hide_on_screen' => '',
            'active' => true,
            'description' => '',
            'show_in_rest' => 0,
        ) );

        // Earnings and Deductions
        acf_add_local_field_group( array(
            'key' => 'group_5e5547561c2eb',
            'title' => 'Earnings and Deductions',
            'fields' => array(
                array(
                    'key' => 'field_65e0d91927d53',
                    'label' => 'Gross Pay YTD',
                    'name' => 'gross_pay_ytd',
                    'aria-label' => '',
                    'type' => 'number',
                    'instructions' => 'Gross Pay, including Sick Pay',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '20',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'min' => '',
                    'max' => '',
                    'placeholder' => '',
                    'step' => '',
                    'prepend' => '$',
                    'append' => '',
                ),
                array(
                    'key' => 'field_65e73abc8ad78',
                    'label' => 'Sick Pay YTD',
                    'name' => 'sick_pay_ytd',
                    'aria-label' => '',
                    'type' => 'number',
                    'instructions' => 'Gross Pay',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '20',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'min' => '',
                    'max' => '',
                    'placeholder' => '',
                    'step' => '',
                    'prepend' => '$',
                    'append' => '',
                ),
                array(
                    'key' => 'field_65e0d94e27d54',
                    'label' => 'Basis of pay',
                    'name' => 'basis_of_pay',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '(e.g. Hourly)',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '20',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'maxlength' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                ),
                array(
                    'key' => 'field_65e0d6b3bcb93',
                    'label' => 'Sick Hours Available',
                    'name' => 'sick_hrs_avail',
                    'aria-label' => '',
                    'type' => 'number',
                    'instructions' => '(this period)',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '20',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'min' => '',
                    'max' => '',
                    'placeholder' => '',
                    'step' => '',
                    'prepend' => '',
                    'append' => '',
                ),
                array(
                    'key' => 'field_65e0d656bcb92',
                    'label' => 'Total Hours Worked',
                    'name' => 'total_hours_worked',
                    'aria-label' => '',
                    'type' => 'number',
                    'instructions' => '(this period)',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '20',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'min' => '',
                    'max' => '',
                    'placeholder' => '',
                    'step' => '',
                    'prepend' => '',
                    'append' => '',
                ),
                array(
                    'key' => 'field_65e0d7189e897',
                    'label' => 'Earnings Breakdown',
                    'name' => '',
                    'aria-label' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '25',
                        'class' => '',
                        'id' => '',
                    ),
                    'placement' => 'top',
                    'endpoint' => 0,
                    'selected' => 0,
                ),
                array(
                    'key' => 'field_5e5547752ddf5',
                    'label' => 'Earnings',
                    'name' => 'earnings',
                    'aria-label' => '',
                    'type' => 'repeater',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'layout' => 'table',
                    'pagination' => 0,
                    'min' => 0,
                    'max' => 0,
                    'collapsed' => '',
                    'button_label' => 'Add Row',
                    'rows_per_page' => 20,
                    'sub_fields' => array(
                        array(
                            'key' => 'field_5e554860e2c5d',
                            'label' => 'Description',
                            'name' => 'earnings_description',
                            'aria-label' => '',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                            'parent_repeater' => 'field_5e5547752ddf5',
                        ),
                        array(
                            'key' => 'field_5e5547b62ddf6',
                            'label' => 'Rate',
                            'name' => 'earnings_rate',
                            'aria-label' => '',
                            'type' => 'number',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '$',
                            'append' => '',
                            'min' => '',
                            'max' => '',
                            'step' => '',
                            'parent_repeater' => 'field_5e5547752ddf5',
                        ),
                        array(
                            'key' => 'field_5e5547e02ddf7',
                            'label' => 'Units',
                            'name' => 'earnings_units',
                            'aria-label' => '',
                            'type' => 'number',
                            'instructions' => 'AKA hours',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'min' => '',
                            'max' => '',
                            'placeholder' => '',
                            'step' => '',
                            'prepend' => '',
                            'append' => '',
                            'parent_repeater' => 'field_5e5547752ddf5',
                        ),
                        array(
                            'key' => 'field_5e55481bf6d17',
                            'label' => 'Total this period',
                            'name' => 'earnings_subtotal',
                            'aria-label' => '',
                            'type' => 'number',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '$',
                            'append' => '',
                            'min' => '',
                            'max' => '',
                            'step' => '',
                            'parent_repeater' => 'field_5e5547752ddf5',
                        ),
                    ),
                ),
                array(
                    'key' => 'field_65e0d6f0b1606',
                    'label' => 'Deductions/Withholding',
                    'name' => '',
                    'aria-label' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '25',
                        'class' => '',
                        'id' => '',
                    ),
                    'placement' => 'top',
                    'endpoint' => 0,
                    'selected' => 0,
                ),
                array(
                    'key' => 'field_5e768e2ae917f',
                    'label' => 'Deductions/Withholding',
                    'name' => 'deductions',
                    'aria-label' => '',
                    'type' => 'repeater',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'formula' => '',
                    'calculated_format' => '',
                    'blank_if_zero' => 0,
                    'readonly' => 0,
                    'layout' => 'table',
                    'pagination' => 0,
                    'min' => 0,
                    'max' => 0,
                    'collapsed' => '',
                    'button_label' => 'Add Row',
                    'rows_per_page' => 20,
                    'sub_fields' => array(
                        array(
                            'key' => 'field_5e768e43e9180',
                            'label' => 'Deduction Category',
                            'name' => 'deduction_category',
                            'aria-label' => '',
                            'type' => 'taxonomy',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'taxonomy' => 'tax_category',
                            'add_term' => 1,
                            'save_terms' => 0,
                            'load_terms' => 0,
                            'return_format' => 'id',
                            'field_type' => 'select',
                            'allow_null' => 0,
                            'multiple' => 0,
                            'bidirectional_target' => array(
                            ),
                            'parent_repeater' => 'field_5e768e2ae917f',
                        ),
                        array(
                            'key' => 'field_5e768e53e9181',
                            'label' => 'Deduction Amount',
                            'name' => 'deduction_amount',
                            'aria-label' => '',
                            'type' => 'number',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '$',
                            'append' => '',
                            'min' => '',
                            'max' => '',
                            'step' => '',
                            'parent_repeater' => 'field_5e768e2ae917f',
                        ),
                    ),
                ),
                array(
                    'key' => 'field_65e132001c11c',
                    'label' => 'X-check',
                    'name' => '',
                    'aria-label' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '25',
                        'class' => '',
                        'id' => '',
                    ),
                    'placement' => 'top',
                    'endpoint' => 0,
                    'selected' => 0,
                ),
                array(
                    'key' => 'field_5e769432e4c1d',
                    'label' => 'Total Earnings',
                    'name' => 'total_earnings',
                    'aria-label' => '',
                    'type' => 'number',
                    'instructions' => 'Gross Pay (calc from earnings repeater)',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '25',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'min' => '',
                    'max' => '',
                    'placeholder' => '',
                    'step' => '',
                    'prepend' => '$',
                    'append' => '',
                ),
                array(
                    'key' => 'field_5e7694e12669a',
                    'label' => 'Total Deductions',
                    'name' => 'total_deductions',
                    'aria-label' => '',
                    'type' => 'number',
                    'instructions' => 'Total deductions (calc from deductions repeater)',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '25',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'min' => '',
                    'max' => '',
                    'placeholder' => '',
                    'step' => '',
                    'prepend' => '$',
                    'append' => '',
                ),
                array(
                    'key' => 'field_5e76a116a9477',
                    'label' => 'Net Pay X-check',
                    'name' => 'net_xcheck',
                    'aria-label' => '',
                    'type' => 'number',
                    'instructions' => 'Gross Pay minus Total Deductions (calc)',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '25',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'min' => '',
                    'max' => '',
                    'placeholder' => '',
                    'step' => '',
                    'prepend' => '$',
                    'append' => '',
                ),
            ),
            'location' => [
                [
                    [
                        'param'    => 'post_type',
                        'operator' => '==',
                        'value'    => 'document',
                    ],
                    [
                        'param'    => 'post_taxonomy',
                        'operator' => '==',
                        'value' => 'document_category:work-payments',
                    ],
                ],
                [
                    [
                        'param'    => 'post_type',
                        'operator' => '==',
                        'value'    => 'document',
                    ],
                    [
                        'param'    => 'post_taxonomy',
                        'operator' => '==',
                        'value' => 'document_category:earnings-statements',
                    ],
                ],
            ],
            'menu_order' => 0,
            'position' => 'normal',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'field',
            'hide_on_screen' => '',
            'active' => true,
            'description' => '',
            'show_in_rest' => 0,
        ) );

        // Not in use
        acf_add_local_field_group([
            'key' => 'group_workpayment_details',
            'title' => 'Work Payment Details (WIP)',
            'fields' => [
                /*[
                    'key'   => 'field_bkkp_employment_employer_ein',
                    'name'  => 'bkkp_employment_employer_ein',
                    'label' => 'EIN',
                    'type'  => 'text',
                ],*/
                [
                    'key'           => 'field_bkkp_employment_employer',
                    'name'          => 'bkkp_employment_employer',
                    'label'         => 'Employer',
                    'type'          => 'post_object',
                    'post_type'     => ['employer'],
                    'return_format' => 'id',
                ],
                [
                    'key'    => 'field_bkkp_employment_gross_pay',
                    'name'   => 'bkkp_employment_gross_pay',
                    'label'  => 'Gross Pay',
                    'type'   => 'number',
                    'prepend'=> '$',
                ],
                [
                    'key'   => 'field_bkkp_employment_pay_period_start',
                    'name'  => 'bkkp_employment_pay_period_start',
                    'label' => 'Pay Period Start',
                    'type'  => 'date_picker',
                ],
                [
                    'key'   => 'field_bkkp_employment_pay_period_end',
                    'name'  => 'bkkp_employment_pay_period_end',
                    'label' => 'Pay Period End',
                    'type'  => 'date_picker',
                ],
                [
                    'key'   => 'field_bkkp_employment_tax_year',
                    'name'  => 'bkkp_employment_tax_year',
                    'label' => 'Tax Year',
                    'type'  => 'text',
                ],
                [
                    'key'           => 'field_bkkp_employment_document',
                    'name'          => 'bkkp_employment_document',
                    'label'         => 'Attached Document',
                    'type'          => 'file',
                    'return_format' => 'url',
                ],
            ],
            'location' => [
                [
                    [
                        'param' => 'post_type',
                        'operator' => '==',
                        'value' => 'workpayment',
                    ],
                ],
            ],
        ]);
    }
}
