<?php

namespace atc\Bkkp\Modules\Accounting\Fields;
//namespace atc\WHx4\Modules\Employment\Fields;

use atc\WHx4\Core\Contracts\FieldGroupInterface;

// TODO: rename all fields (keys/names) according to whx4 naming conventions
// TODO: make this final class?
class AccountFields implements FieldGroupInterface
{
    public static function register(): void
    {
        //error_log( '=== EmployerFields: register()) ===' );
        if ( !function_exists('acf_add_local_field_group') ) return;

        //use atc\WHx4\Migrations\FieldKeyMigrator;
        /*
        // Migrate
        FieldKeyMigrator::migrate([
            'field_624775f4b6221' => [
                'new_field_key' => 'field_rex_modulename_first_name',
                'old_meta_key'  => 'first_name',
                'new_meta_key'  => 'rex_modulename_first_name',
            ],
            'field_abc123xyz456' => [
                'new_field_key' => 'field_rex_notes',
                // no meta_key rename
            ],
        ]);
        */

        acf_add_local_field_group([
            'key' => 'group_account_details',
            'title' => 'Account Details',
            'fields' => [
                [
                    'key' => 'field_65ceccb977c8c',
                    'label' => 'Institution/Company/Organization',
                    'name' => 'groups_accounts',
                    'aria-label' => '',
                    'type' => 'post_object',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '20',
                        'class' => '',
                        'id' => '',
                    ],
                    'post_type' => [
                        0 => 'group',
                    ],
                    'post_status' => '',
                    'taxonomy' => '',
                    'return_format' => 'object',
                    'multiple' => 0,
                    'allow_null' => 0,
                    'bidirectional' => 0,
                    'ui' => 1,
                    'bidirectional_target' => [
                    ],
                ],
                [
                    'key' => 'field_65cf86fcc3703',
                    'label' => 'Account Status',
                    'name' => 'account_status',
                    'aria-label' => '',
                    'type' => 'select',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '15',
                        'class' => '',
                        'id' => '',
                    ],
                    'choices' => [
                        'active' => 'Active',
                        'dormant' => 'Dormant -- Open but inactive',
                        'inactive' => 'Inactive',
                        'closed' => 'Closed',
                        'cancelled' => 'Cancelled',
                    ],
                    'default_value' => false,
                    'return_format' => 'value',
                    'multiple' => 0,
                    'allow_null' => 0,
                    'ui' => 0,
                    'ajax' => 0,
                    'placeholder' => '',
                ],
                [
                    'key' => 'field_65cf89ac3a8bc',
                    'label' => 'Account Number',
                    'name' => 'account_num',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '15',
                        'class' => '',
                        'id' => '',
                    ],
                    'default_value' => '',
                    'maxlength' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                ],
                [
                    'key' => 'field_630788ed338ca',
                    'label' => 'Last 4 Digits',
                    'name' => 'last4',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '10',
                        'class' => '',
                        'id' => '',
                    ],
                    'default_value' => '',
                    'maxlength' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                ],
                [
                    'key' => 'field_661ac00174088',
                    'label' => 'Full Name',
                    'name' => 'full_name',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '25',
                        'class' => '',
                        'id' => '',
                    ],
                    'default_value' => '',
                    'maxlength' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                ],
                [
                    'key' => 'field_661ac01374089',
                    'label' => 'Abbr',
                    'name' => 'abbr',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '10',
                        'class' => '',
                        'id' => '',
                    ],
                    'default_value' => '',
                    'maxlength' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                ],
                [
                    'key' => 'field_63078963b9656',
                    'label' => 'Date Opened',
                    'name' => 'date_opened',
                    'aria-label' => '',
                    'type' => 'date_picker',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '15',
                        'class' => '',
                        'id' => '',
                    ],
                    'display_format' => 'm/d/Y',
                    'return_format' => 'm/d/Y',
                    'first_day' => 0,
                ],
                [
                    'key' => 'field_63078971b9657',
                    'label' => 'Date Closed',
                    'name' => 'date_closed',
                    'aria-label' => '',
                    'type' => 'date_picker',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '15',
                        'class' => '',
                        'id' => '',
                    ],
                    'display_format' => 'm/d/Y',
                    'return_format' => 'm/d/Y',
                    'first_day' => 0,
                ],
                [
                    'key' => 'field_680a3cad4bf49',
                    'label' => 'Login URL',
                    'name' => 'login_url',
                    'aria-label' => '',
                    'type' => 'url',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '25',
                        'class' => '',
                        'id' => '',
                    ],
                    'default_value' => '',
                    'allow_in_bindings' => 0,
                    'placeholder' => '',
                ],
                [
                    'key' => 'field_630788806a189',
                    'label' => 'Account Type TMP',
                    'name' => 'account_type_tmp',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '15',
                        'class' => '',
                        'id' => '',
                    ],
                    'default_value' => '',
                    'maxlength' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                ],
                [
                    'key' => 'field_6307888c6a18a',
                    'label' => 'Account Status TMP',
                    'name' => 'account_status_tmp',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '15',
                        'class' => '',
                        'id' => '',
                    ],
                    'default_value' => '',
                    'maxlength' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                ],
                [
                    'key' => 'field_63078b72ac80e',
                    'label' => 'Promotions TMP',
                    'name' => 'promotions_tmp',
                    'aria-label' => '',
                    'type' => 'wysiwyg',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ],
                    'formula' => '',
                    'calculated_format' => '',
                    'blank_if_zero' => 0,
                    'default_value' => '',
                    'tabs' => 'all',
                    'toolbar' => 'basic',
                    'media_upload' => 1,
                    'delay' => 0,
                ],
                [
                    'key' => 'field_630788c545de0',
                    'label' => 'Notes',
                    'name' => 'notes',
                    'aria-label' => '',
                    'type' => 'wysiwyg',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => [
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ],
                    'formula' => '',
                    'calculated_format' => '',
                    'blank_if_zero' => 0,
                    'default_value' => '',
                    'tabs' => 'all',
                    'toolbar' => 'basic',
                    'media_upload' => 1,
                    'delay' => 0,
                ],
            ],
            'location' => [
                [
                    [
                        'param' => 'post_type',
                        'operator' => '==',
                        'value' => 'account',
                    ],
                ],
            ],
        ]);
    }
}
