<?php

namespace atc\Bkkp\Modules\Accounting\Fields;

use WXC\Core\Contracts\FieldGroupInterface;
use WXC\Core\Contracts\PostTypeFieldGroupInterface;

final class GroupFields implements FieldGroupInterface, PostTypeFieldGroupInterface
{
    public function getPostType(): string
    {
        return 'group';
    }

    public static function register(): void
    {
        if ( ! function_exists( 'acf_add_local_field_group' ) ) {
            return;
        }

        // Organization/Group Details
        acf_add_local_field_group( array(
            'key' => 'group_62a11b45c148f', //'field_rex_moneybags_group_fields',
            'title' => 'BKKP Organization/Group Details',
            'fields' => array(
                [
                    'key'   => 'field_whx4_bkkp_ledger_code',
                    'name'  => 'whx4_bkkp_ledger_code',
                    'label' => 'Ledger Code',
                    'type'  => 'text',
                ],
                array(
                    'key' => 'field_62a11b50f3558',
                    'label' => 'Basics',
                    'name' => '',
                    'aria-label' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'formula' => '',
                    'calculated_format' => '',
                    'blank_if_zero' => 0,
                    'placement' => 'top',
                    'endpoint' => 0,
                    'selected' => 0,
                ),
                array(
                    'key' => 'field_62a11b7bf3559',
                    'label' => 'Full Name',
                    'name' => 'full_name',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '25',
                        'class' => '',
                        'id' => '',
                    ),
                    'formula' => '',
                    'calculated_format' => '',
                    'blank_if_zero' => 0,
                    'readonly' => 0,
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
                array(
                    'key' => 'field_62a11b80f355a',
                    'label' => 'Abbr',
                    'name' => 'abbr',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '25',
                        'class' => '',
                        'id' => '',
                    ),
                    'formula' => '',
                    'calculated_format' => '',
                    'blank_if_zero' => 0,
                    'readonly' => 0,
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
                array(
                    'key' => 'field_62a11b85f355b',
                    'label' => 'Website',
                    'name' => 'url',
                    'aria-label' => '',
                    'type' => 'url',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '25',
                        'class' => '',
                        'id' => '',
                    ),
                    'formula' => '',
                    'calculated_format' => '',
                    'blank_if_zero' => 0,
                    'readonly' => 0,
                    'default_value' => '',
                    'placeholder' => '',
                ),
                array(
                    'key' => 'field_62a11b8ff355c',
                    'label' => 'Jobs URL',
                    'name' => 'jobs_url',
                    'aria-label' => '',
                    'type' => 'url',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '25',
                        'class' => '',
                        'id' => '',
                    ),
                    'formula' => '',
                    'calculated_format' => '',
                    'blank_if_zero' => 0,
                    'readonly' => 0,
                    'default_value' => '',
                    'placeholder' => '',
                ),
                array(
                    'key' => 'field_62a11b98f355d',
                    'label' => 'Phone Number',
                    'name' => 'phone_number',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '25',
                        'class' => '',
                        'id' => '',
                    ),
                    'formula' => '',
                    'calculated_format' => '',
                    'blank_if_zero' => 0,
                    'readonly' => 0,
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
                array(
                    'key' => 'field_62a11ba3f355e',
                    'label' => 'Email Address',
                    'name' => 'email_address',
                    'aria-label' => '',
                    'type' => 'email',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '25',
                        'class' => '',
                        'id' => '',
                    ),
                    'formula' => '',
                    'calculated_format' => '',
                    'blank_if_zero' => 0,
                    'readonly' => 0,
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                ),
                array(
                    'key' => 'field_62a11bb1f355f',
                    'label' => 'Email TMP',
                    'name' => 'email',
                    'aria-label' => '',
                    'type' => 'email',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '25',
                        'class' => '',
                        'id' => '',
                    ),
                    'formula' => '',
                    'calculated_format' => '',
                    'blank_if_zero' => 0,
                    'readonly' => 0,
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                ),
                array(
                    'key' => 'field_62a11bdef3562',
                    'label' => 'Business Hours',
                    'name' => 'hours',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '25',
                        'class' => '',
                        'id' => '',
                    ),
                    'formula' => '',
                    'calculated_format' => '',
                    'blank_if_zero' => 0,
                    'readonly' => 0,
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
                array(
                    'key' => 'field_62a11c4bf3569',
                    'label' => 'Address',
                    'name' => '',
                    'aria-label' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'formula' => '',
                    'calculated_format' => '',
                    'blank_if_zero' => 0,
                    'placement' => 'top',
                    'endpoint' => 0,
                    'selected' => 0,
                ),
                array(
                    'key' => 'field_62a11c5af356a',
                    'label' => 'Street Address',
                    'name' => 'street_address',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'formula' => '',
                    'calculated_format' => '',
                    'blank_if_zero' => 0,
                    'readonly' => 0,
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
                array(
                    'key' => 'field_62a11c62f356b',
                    'label' => 'City',
                    'name' => 'city',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '25',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'maxlength' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                ),
                array(
                    'key' => 'field_62a11c67f356c',
                    'label' => 'State',
                    'name' => 'state',
                    'aria-label' => '',
                    'type' => 'select',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '15',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => array(
                        'AL' => 'Alabama',
                        'AK' => 'Alaska',
                        'AZ' => 'Arizona',
                        'AR' => 'Arkansas',
                        'CA' => 'California',
                        'CO' => 'Colorado',
                        'CT' => 'Connecticut',
                        'DE' => 'Delaware',
                        'DC' => 'District of Columbia',
                        'FL' => 'Florida',
                        'GA' => 'Georgia',
                        'HI' => 'Hawaii',
                        'ID' => 'Idaho',
                        'IL' => 'Illinois',
                        'IN' => 'Indiana',
                        'IA' => 'Iowa',
                        'KS' => 'Kansas',
                        'KY' => 'Kentucky',
                        'LA' => 'Louisiana',
                        'ME' => 'Maine',
                        'MD' => 'Maryland',
                        'MA' => 'Massachusetts',
                        'MI' => 'Michigan',
                        'MN' => 'Minnesota',
                        'MS' => 'Mississippi',
                        'MO' => 'Missouri',
                        'MT' => 'Montana',
                        'NE' => 'Nebraska',
                        'NV' => 'Nevada',
                        'NH' => 'New Hampshire',
                        'NJ' => 'New Jersey',
                        'NM' => 'New Mexico',
                        'NY' => 'New York',
                        'NC' => 'North Carolina',
                        'ND' => 'North Dakota',
                        'OH' => 'Ohio',
                        'OK' => 'Oklahoma',
                        'OR' => 'Oregon',
                        'PA' => 'Pennsylvania',
                        'RI' => 'Rhode Island',
                        'SC' => 'South Carolina',
                        'SD' => 'South Dakota',
                        'TN' => 'Tennessee',
                        'TX' => 'Texas',
                        'UT' => 'Utah',
                        'VT' => 'Vermont',
                        'VA' => 'Virginia',
                        'WA' => 'Washington',
                        'WV' => 'West Virginia',
                        'WI' => 'Wisconsin',
                        'WY' => 'Wyoming',
                    ),
                    'default_value' => false,
                    'return_format' => 'value',
                    'multiple' => 0,
                    'allow_null' => 0,
                    'ui' => 0,
                    'ajax' => 0,
                    'placeholder' => '',
                    'create_options' => 0,
                    'save_options' => 0,
                ),
                array(
                    'key' => 'field_62a11c6bf356d',
                    'label' => 'Zip Code',
                    'name' => 'zip_code',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '15',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'maxlength' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                ),
                array(
                    'key' => 'field_62a11c72f356e',
                    'label' => 'Country',
                    'name' => 'country',
                    'aria-label' => '',
                    'type' => 'select',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '25',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => array(
                        'afghanistan' => 'Afghanistan',
                        'albania' => 'Albania',
                        'algeria' => 'Algeria',
                        'american_samoa' => 'American Samoa',
                        'andorra' => 'Andorra',
                        'angola' => 'Angola',
                        'anguilla' => 'Anguilla',
                        'antigua_and_barbuda' => 'Antigua and Barbuda',
                        'argentina' => 'Argentina',
                        'armenia' => 'Armenia',
                        'aruba' => 'Aruba',
                        'australia' => 'Australia',
                        'austria' => 'Austria',
                        'azerbaijan' => 'Azerbaijan',
                        'bahamas' => 'Bahamas',
                        'bahrain' => 'Bahrain',
                        'bangladesh' => 'Bangladesh',
                        'barbados' => 'Barbados',
                        'belarus' => 'Belarus',
                        'belgium' => 'Belgium',
                        'belize' => 'Belize',
                        'benin' => 'Benin',
                        'bermuda' => 'Bermuda',
                        'bhutan' => 'Bhutan',
                        'bolivia' => 'Bolivia',
                        'bosnia-herzegovina' => 'Bosnia-Herzegovina',
                        'botswana' => 'Botswana',
                        'bouvet_island' => 'Bouvet Island',
                        'brazil' => 'Brazil',
                        'brunei' => 'Brunei',
                        'bulgaria' => 'Bulgaria',
                        'burkina_faso' => 'Burkina Faso',
                        'burundi' => 'Burundi',
                        'cambodia' => 'Cambodia',
                        'cameroon' => 'Cameroon',
                        'canada' => 'Canada',
                        'cape_verde' => 'Cape Verde',
                        'cayman_islands' => 'Cayman Islands',
                        'central_african_republic' => 'Central African Republic',
                        'chad' => 'Chad',
                        'chile' => 'Chile',
                        'china' => 'China',
                        'christmas_island' => 'Christmas Island',
                        'cocos_keeling_islands' => 'Cocos (Keeling) Islands',
                        'colombia' => 'Colombia',
                        'comoros' => 'Comoros',
                        'congo_democratic_republic_of_the_zaire' => 'Congo, Democratic Republic of the (Zaire)',
                        'congo_republic_of' => 'Congo, Republic of',
                        'cook_islands' => 'Cook Islands',
                        'costa_rica' => 'Costa Rica',
                        'croatia' => 'Croatia',
                        'cuba' => 'Cuba',
                        'cyprus' => 'Cyprus',
                        'czech_republic' => 'Czech Republic',
                        'denmark' => 'Denmark',
                        'djibouti' => 'Djibouti',
                        'dominica' => 'Dominica',
                        'dominican_republic' => 'Dominican Republic',
                        'ecuador' => 'Ecuador',
                        'egypt' => 'Egypt',
                        'el_salvador' => 'El Salvador',
                        'equatorial_guinea' => 'Equatorial Guinea',
                        'eritrea' => 'Eritrea',
                        'estonia' => 'Estonia',
                        'ethiopia' => 'Ethiopia',
                        'falkland_islands' => 'Falkland Islands',
                        'faroe_islands' => 'Faroe Islands',
                        'fiji' => 'Fiji',
                        'finland' => 'Finland',
                        'france' => 'France',
                        'french_guiana' => 'French Guiana',
                        'gabon' => 'Gabon',
                        'gambia' => 'Gambia',
                        'georgia' => 'Georgia',
                        'germany' => 'Germany',
                        'ghana' => 'Ghana',
                        'gibraltar' => 'Gibraltar',
                        'greece' => 'Greece',
                        'greenland' => 'Greenland',
                        'grenada' => 'Grenada',
                        'guadeloupe_french' => 'Guadeloupe (French)',
                        'guam_usa' => 'Guam (USA)',
                        'guatemala' => 'Guatemala',
                        'guinea' => 'Guinea',
                        'guinea_bissau' => 'Guinea Bissau',
                        'guyana' => 'Guyana',
                        'haiti' => 'Haiti',
                        'holy_see' => 'Holy See',
                        'honduras' => 'Honduras',
                        'hong_kong' => 'Hong Kong',
                        'hungary' => 'Hungary',
                        'iceland' => 'Iceland',
                        'india' => 'India',
                        'indonesia' => 'Indonesia',
                        'iran' => 'Iran',
                        'iraq' => 'Iraq',
                        'ireland' => 'Ireland',
                        'israel' => 'Israel',
                        'italy' => 'Italy',
                        'ivory_coast_cote_d-ivoire' => 'Ivory Coast (Cote D`Ivoire)',
                        'jamaica' => 'Jamaica',
                        'japan' => 'Japan',
                        'jordan' => 'Jordan',
                        'kazakhstan' => 'Kazakhstan',
                        'kenya' => 'Kenya',
                        'kiribati' => 'Kiribati',
                        'kuwait' => 'Kuwait',
                        'kyrgyzstan' => 'Kyrgyzstan',
                        'laos' => 'Laos',
                        'latvia' => 'Latvia',
                        'lebanon' => 'Lebanon',
                        'lesotho' => 'Lesotho',
                        'liberia' => 'Liberia',
                        'libya' => 'Libya',
                        'liechtenstein' => 'Liechtenstein',
                        'lithuania' => 'Lithuania',
                        'luxembourg' => 'Luxembourg',
                        'macau' => 'Macau',
                        'macedonia' => 'Macedonia',
                        'madagascar' => 'Madagascar',
                        'malawi' => 'Malawi',
                        'malaysia' => 'Malaysia',
                        'maldives' => 'Maldives',
                        'mali' => 'Mali',
                        'malta' => 'Malta',
                        'marshall_islands' => 'Marshall Islands',
                        'martinique_french' => 'Martinique (French)',
                        'mauritania' => 'Mauritania',
                        'mauritius' => 'Mauritius',
                        'mayotte' => 'Mayotte',
                        'mexico' => 'Mexico',
                        'micronesia' => 'Micronesia',
                        'moldova' => 'Moldova',
                        'monaco' => 'Monaco',
                        'mongolia' => 'Mongolia',
                        'montenegro' => 'Montenegro',
                        'montserrat' => 'Montserrat',
                        'morocco' => 'Morocco',
                        'mozambique' => 'Mozambique',
                        'myanmar' => 'Myanmar',
                        'namibia' => 'Namibia',
                        'nauru' => 'Nauru',
                        'nepal' => 'Nepal',
                        'netherlands' => 'Netherlands',
                        'netherlands_antilles' => 'Netherlands Antilles',
                        'new_caledonia_french' => 'New Caledonia (French)',
                        'new_zealand' => 'New Zealand',
                        'nicaragua' => 'Nicaragua',
                        'niger' => 'Niger',
                        'nigeria' => 'Nigeria',
                        'niue' => 'Niue',
                        'norfolk_island' => 'Norfolk Island',
                        'north_korea' => 'North Korea',
                        'northern_mariana_islands' => 'Northern Mariana Islands',
                        'norway' => 'Norway',
                        'oman' => 'Oman',
                        'pakistan' => 'Pakistan',
                        'palau' => 'Palau',
                        'panama' => 'Panama',
                        'papua_new_guinea' => 'Papua New Guinea',
                        'paraguay' => 'Paraguay',
                        'peru' => 'Peru',
                        'philippines' => 'Philippines',
                        'pitcairn_island' => 'Pitcairn Island',
                        'poland' => 'Poland',
                        'polynesia_french' => 'Polynesia (French)',
                        'portugal' => 'Portugal',
                        'puerto_rico' => 'Puerto Rico',
                        'qatar' => 'Qatar',
                        'reunion' => 'Reunion',
                        'romania' => 'Romania',
                        'russia' => 'Russia',
                        'rwanda' => 'Rwanda',
                        'saint_helena' => 'Saint Helena',
                        'saint_kitts_and_nevis' => 'Saint Kitts and Nevis',
                        'saint_lucia' => 'Saint Lucia',
                        'saint_pierre_and_miquelon' => 'Saint Pierre and Miquelon',
                        'saint_vincent_and_grenadines' => 'Saint Vincent and Grenadines',
                        'samoa' => 'Samoa',
                        'san_marino' => 'San Marino',
                        'sao_tome_and_principe' => 'Sao Tome and Principe',
                        'saudi_arabia' => 'Saudi Arabia',
                        'senegal' => 'Senegal',
                        'serbia' => 'Serbia',
                        'seychelles' => 'Seychelles',
                        'sierra_leone' => 'Sierra Leone',
                        'singapore' => 'Singapore',
                        'slovakia' => 'Slovakia',
                        'slovenia' => 'Slovenia',
                        'solomon_islands' => 'Solomon Islands',
                        'somalia' => 'Somalia',
                        'south_africa' => 'South Africa',
                        'south_georgia_and_south_sandwich_islands' => 'South Georgia and South Sandwich Islands',
                        'south_korea' => 'South Korea',
                        'south_sudan' => 'South Sudan',
                        'spain' => 'Spain',
                        'sri_lanka' => 'Sri Lanka',
                        'sudan' => 'Sudan',
                        'suriname' => 'Suriname',
                        'svalbard_and_jan_mayen_islands' => 'Svalbard and Jan Mayen Islands',
                        'swaziland' => 'Swaziland',
                        'sweden' => 'Sweden',
                        'switzerland' => 'Switzerland',
                        'syria' => 'Syria',
                        'taiwan' => 'Taiwan',
                        'tajikistan' => 'Tajikistan',
                        'tanzania' => 'Tanzania',
                        'thailand' => 'Thailand',
                        'timor-leste' => 'Timor-Leste (East Timor)',
                        'togo' => 'Togo',
                        'tokelau' => 'Tokelau',
                        'tonga' => 'Tonga',
                        'trinidad_and_tobago' => 'Trinidad and Tobago',
                        'tunisia' => 'Tunisia',
                        'turkey' => 'Turkey',
                        'turkmenistan' => 'Turkmenistan',
                        'turks_and_caicos_islands' => 'Turks and Caicos Islands',
                        'tuvalu' => 'Tuvalu',
                        'uganda' => 'Uganda',
                        'ukraine' => 'Ukraine',
                        'united_arab_emirates' => 'United Arab Emirates',
                        'united_kingdom' => 'United Kingdom',
                        'usa' => 'United States',
                        'uruguay' => 'Uruguay',
                        'uzbekistan' => 'Uzbekistan',
                        'vanuatu' => 'Vanuatu',
                        'venezuela' => 'Venezuela',
                        'vietnam' => 'Vietnam',
                        'virgin_islands' => 'Virgin Islands',
                        'wallis_and_futuna_islands' => 'Wallis and Futuna Islands',
                        'yemen' => 'Yemen',
                        'zambia' => 'Zambia',
                        'zimbabwe' => 'Zimbabwe',
                    ),
                    'default_value' => false,
                    'return_format' => 'value',
                    'multiple' => 0,
                    'allow_null' => 0,
                    'ui' => 0,
                    'ajax' => 0,
                    'placeholder' => '',
                    'create_options' => 0,
                    'save_options' => 0,
                ),
                array(
                    'key' => 'field_62a11c76f356f',
                    'label' => 'Related Content',
                    'name' => '',
                    'aria-label' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'formula' => '',
                    'calculated_format' => '',
                    'blank_if_zero' => 0,
                    'placement' => 'top',
                    'endpoint' => 0,
                    'selected' => 0,
                ),
                array(
                    'key' => 'field_62a11c89f3570',
                    'label' => 'Related Person(s)',
                    'name' => 'related_persons',
                    'aria-label' => '',
                    'type' => 'post_object',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'post_type' => array(
                        0 => 'person',
                    ),
                    'post_status' => '',
                    'taxonomy' => '',
                    'return_format' => 'object',
                    'multiple' => 1,
                    'allow_null' => 0,
                    'allow_in_bindings' => 1,
                    'bidirectional' => 0,
                    'ui' => 1,
                    'bidirectional_target' => array(
                    ),
                ),
                array(
                    'key' => 'field_62a11c9ef3571',
                    'label' => 'Related Location(s) Bi-directional',
                    'name' => 'groups_locations',
                    'aria-label' => '',
                    'type' => 'post_object',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'post_type' => array(
                        0 => 'location',
                    ),
                    'post_status' => '',
                    'taxonomy' => '',
                    'return_format' => 'object',
                    'multiple' => 1,
                    'allow_null' => 0,
                    'allow_in_bindings' => 1,
                    'bidirectional' => 0,
                    'ui' => 1,
                    'bidirectional_target' => array(
                    ),
                ),
                array(
                    'key' => 'field_6759ef08b1728',
                    'label' => 'Events',
                    'name' => '',
                    'aria-label' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'placement' => 'top',
                    'endpoint' => 0,
                    'selected' => 0,
                ),
                array(
                    'key' => 'field_62a11cbbf3572',
                    'label' => 'Related Event(s) ACF',
                    'name' => 'related_events_acf',
                    'aria-label' => '',
                    'type' => 'relationship',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'post_type' => array(
                        0 => 'event',
                    ),
                    'post_status' => '',
                    'taxonomy' => '',
                    'filters' => array(
                        0 => 'search',
                        1 => 'taxonomy',
                    ),
                    'return_format' => 'object',
                    'min' => '',
                    'max' => '',
                    'allow_in_bindings' => 1,
                    'elements' => '',
                    'bidirectional' => 0,
                    'bidirectional_target' => array(
                    ),
                ),
                array(
                    'key' => 'field_64127f60f7da0',
                    'label' => 'Related Event(s) v2 Bidirectional',
                    'name' => 'groups_events',
                    'aria-label' => '',
                    'type' => 'relationship',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'post_type' => array(
                        0 => 'event',
                    ),
                    'post_status' => '',
                    'taxonomy' => '',
                    'filters' => array(
                        0 => 'search',
                        1 => 'taxonomy',
                    ),
                    'return_format' => 'object',
                    'min' => '',
                    'max' => '',
                    'allow_in_bindings' => 1,
                    'elements' => '',
                    'bidirectional' => 0,
                    'bidirectional_target' => array(
                    ),
                ),
                array(
                    'key' => 'field_6759ef17b1729',
                    'label' => 'Transactions',
                    'name' => '',
                    'aria-label' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'placement' => 'top',
                    'endpoint' => 0,
                    'selected' => 0,
                ),
                array(
                    'key' => 'field_6759eb2826ee6',
                    'label' => 'Related Transactions',
                    'name' => 'related_transactions', // was transactions_events
                    'aria-label' => '',
                    'type' => 'relationship',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'post_type' => array(
                        0 => 'transaction',
                    ),
                    'post_status' => '',
                    'taxonomy' => '',
                    'filters' => array(
                        0 => 'search',
                        1 => 'taxonomy',
                    ),
                    'return_format' => 'id',
                    'min' => '',
                    'max' => '',
                    'allow_in_bindings' => 1,
                    'elements' => '',
                    'bidirectional' => 1,
                    'bidirectional_target' => array(
                        0 => 'field_65cbcd9bca53e',
                    ),
                ),
                array(
                    'key' => 'field_62a121ff2e8a5',
                    'label' => 'Notes',
                    'name' => '',
                    'aria-label' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'formula' => '',
                    'calculated_format' => '',
                    'blank_if_zero' => 0,
                    'placement' => 'top',
                    'endpoint' => 0,
                    'selected' => 0,
                ),
                array(
                    'key' => 'field_62a121f32e8a4',
                    'label' => 'Notes',
                    'name' => 'notes',
                    'aria-label' => '',
                    'type' => 'textarea',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'formula' => '',
                    'calculated_format' => '',
                    'blank_if_zero' => 0,
                    'default_value' => '',
                    'placeholder' => '',
                    'maxlength' => '',
                    'rows' => '',
                    'new_lines' => '',
                ),
            ),
            'location' => array(
                array(
                    array(
                        'param' => 'post_type',
                        'operator' => '==',
                        'value' => 'group',
                    ),
                ),
            ),
            'menu_order' => 0,
            'position' => 'acf_after_title',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => '',
            'active' => true,
            'description' => '',
            'show_in_rest' => 0,
        ) );

        // Mailing List Info
        acf_add_local_field_group( array(
            'key' => 'group_67336301416e7',
            'title' => 'BKKP Mailing List Info',
            'fields' => array(
                array(
                    'key' => 'field_670444f0e4da7',
                    'label' => 'Mailing List Status',
                    'name' => 'mailing_list_status',
                    'aria-label' => '',
                    'type' => 'radio',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '20',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => array(
                        'unknown' => 'Unknown',
                        'subscribed' => 'Subscribed -- Receiving Mailings',
                        'removed' => 'Removed (Requested)',
                    ),
                    'default_value' => '',
                    'return_format' => 'value',
                    'allow_null' => 0,
                    'other_choice' => 0,
                    'allow_in_bindings' => 0,
                    'layout' => 'vertical',
                    'save_other_choice' => 0,
                ),
                array(
                    'key' => 'field_67294c293b80b',
                    'label' => 'Removal Requested?',
                    'name' => 'removal_requested',
                    'aria-label' => '',
                    'type' => 'radio',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '20',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => array(
                        'unknown' => 'Unknown',
                        'todo' => 'To Do',
                        'requested' => 'Requested',
                        'removed' => 'Removed',
                    ),
                    'default_value' => '',
                    'return_format' => 'value',
                    'allow_null' => 0,
                    'other_choice' => 0,
                    'allow_in_bindings' => 0,
                    'layout' => 'vertical',
                    'save_other_choice' => 0,
                ),
                array(
                    'key' => 'field_6704453ae4da8',
                    'label' => 'Mailing List BS',
                    'name' => 'mailing_list_bs',
                    'aria-label' => '',
                    'type' => 'checkbox',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '20',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => array(
                        'labels' => 'Address Labels',
                        'stickers' => 'Stickers',
                        'notepads' => 'Notepads',
                        'cards' => 'Greeting Cards',
                        'certificates' => 'Certificates',
                        'coupons' => 'Coupons',
                        'plastic_swag' => 'Plastic Swag',
                        'duplicates' => 'Duplicate Mailings',
                    ),
                    'default_value' => array(
                    ),
                    'return_format' => 'value',
                    'allow_custom' => 0,
                    'allow_in_bindings' => 0,
                    'layout' => 'vertical',
                    'toggle' => 0,
                    'save_custom' => 0,
                    'custom_choice_button_text' => 'Add new choice',
                ),
                array(
                    'key' => 'field_670449d79876e',
                    'label' => 'Data Web',
                    'name' => 'data_web',
                    'aria-label' => '',
                    'type' => 'checkbox',
                    'instructions' => 'Check this box if this group seems to have acquired my info through the data marketplace, as opposed to a direct request from me.',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '20',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => array(
                        'yes' => 'Yes',
                    ),
                    'default_value' => array(
                    ),
                    'return_format' => 'value',
                    'allow_custom' => 0,
                    'allow_in_bindings' => 0,
                    'layout' => 'vertical',
                    'toggle' => 0,
                    'save_custom' => 0,
                    'custom_choice_button_text' => 'Add new choice',
                ),
                array(
                    'key' => 'field_672958e6a48a0',
                    'label' => 'Address on File',
                    'name' => 'address_on_file',
                    'aria-label' => '',
                    'type' => 'post_object',
                    'instructions' => 'Select the address to which mailings are currently addressed.',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'post_type' => array(
                        0 => 'address',
                    ),
                    'post_status' => '',
                    'taxonomy' => '',
                    'return_format' => 'id',
                    'multiple' => 0,
                    'allow_null' => 0,
                    'allow_in_bindings' => 0,
                    'bidirectional' => 0,
                    'ui' => 1,
                    'bidirectional_target' => array(
                    ),
                ),
                array(
                    'key' => 'field_67294a7911e04',
                    'label' => 'Mailings Received',
                    'name' => 'mailings_received',
                    'aria-label' => '',
                    'type' => 'repeater',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'layout' => 'table',
                    'pagination' => 0,
                    'min' => 0,
                    'max' => 0,
                    'collapsed' => '',
                    'button_label' => 'Add Row',
                    'rows_per_page' => 20,
                    'sub_fields' => array(
                        array(
                            'key' => 'field_67294a8f11e05',
                            'label' => 'Date Received',
                            'name' => 'date_received',
                            'aria-label' => '',
                            'type' => 'date_picker',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'display_format' => 'd/m/Y',
                            'return_format' => 'd/m/Y',
                            'first_day' => 1,
                            'allow_in_bindings' => 0,
                            'default_to_current_date' => 0,
                            'parent_repeater' => 'field_67294a7911e04',
                        ),
                        array(
                            'key' => 'field_67294ae2f0ee9',
                            'label' => 'Description',
                            'name' => 'description',
                            'aria-label' => '',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'maxlength' => '',
                            'allow_in_bindings' => 0,
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'parent_repeater' => 'field_67294a7911e04',
                        ),
                    ),
                ),
            ),
            'location' => array(
                array(
                    array(
                        'param' => 'post_type',
                        'operator' => '==',
                        'value' => 'group',
                    ),
                    array(
                        'param' => 'post_taxonomy',
                        'operator' => '==',
                        'value' => 'group_category:nonprofit-organizations',
                    ),
                ),
                array(
                    array(
                        'param' => 'post_type',
                        'operator' => '==',
                        'value' => 'group',
                    ),
                    array(
                        'param' => 'post_taxonomy',
                        'operator' => '==',
                        'value' => 'group_category:retailers',
                    ),
                ),
            ),
            'menu_order' => 0,
            'position' => 'normal',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => '',
            'active' => true,
            'description' => '',
            'show_in_rest' => 0,
            ) );

        // Nonprofit Info
        acf_add_local_field_group( array(
            'key' => 'group_65ce945a76007',
            'title' => 'BKKP Nonprofit Info',
            'fields' => array(
                array(
                    'key' => 'field_65ce945a2f15c',
                    'label' => 'Charity Navigator Rating',
                    'name' => 'charnav_rating',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => 'e.g. "4-star"',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '20',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'maxlength' => '',
                    'allow_in_bindings' => 1,
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                ),
                array(
                    'key' => 'field_65ce94cc2f15e',
                    'label' => 'American Institute of Philanthropy Rating',
                    'name' => 'aip_rating',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '20',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'maxlength' => '',
                    'allow_in_bindings' => 1,
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                ),
                array(
                    'key' => 'field_65ce94a02f15d',
                    'label' => 'BBB Accredited?',
                    'name' => 'bbb_accredited',
                    'aria-label' => '',
                    'type' => 'true_false',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '20',
                        'class' => '',
                        'id' => '',
                    ),
                    'message' => '',
                    'default_value' => 0,
                    'ui' => 0,
                    'ui_on_text' => '',
                    'ui_off_text' => '',
                ),
            ),
            'location' => array(
                array(
                    array(
                        'param' => 'post_type',
                        'operator' => '==',
                        'value' => 'group',
                    ),
                    array(
                        'param' => 'post_taxonomy',
                        'operator' => '==',
                        'value' => 'group_category:worthy-causes',
                    ),
                ),
                array(
                    array(
                        'param' => 'post_type',
                        'operator' => '==',
                        'value' => 'group',
                    ),
                    array(
                        'param' => 'post_taxonomy',
                        'operator' => '==',
                        'value' => 'group_category:nonprofit-organizations',
                    ),
                ),
            ),
            'menu_order' => 0,
            'position' => 'normal',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'field',
            'hide_on_screen' => '',
            'active' => true,
            'description' => '',
            'show_in_rest' => 0,
        ) );

    }
}
