<?php

namespace atc\Bkkp\Modules\Accounting\Fields;

use atc\WHx4\Core\Contracts\FieldGroupInterface;

final class TransactionFields implements FieldGroupInterface
{
    public static function register(): void
    {
        //error_log( '=== TransactionFields: register()) ===' );
        if ( !function_exists('acf_add_local_field_group') ) return;

        acf_add_local_field_group([
            'key' => 'group_transaction_details',
            'title' => 'Transaction Details',
            'fields' => [
                array(
                    'key' => 'field_660d521730656',
                    'label' => 'Cash Transaction',
                    'name' => 'cash_transaction',
                    'aria-label' => '',
                    'type' => 'true_false',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '20',
                        'class' => '',
                        'id' => '',
                    ),
                    'message' => '',
                    'default_value' => 0,
                    'ui' => 0,
                    'ui_on_text' => '',
                    'ui_off_text' => '',
                ),
                array(
                    'key' => 'field_65cbcd80ca53d',
                    'label' => 'Transaction Info',
                    'name' => '',
                    'aria-label' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '20',
                        'class' => '',
                        'id' => '',
                    ),
                    'placement' => 'top',
                    'endpoint' => 0,
                    'selected' => 0,
                ),
                array(
                    'key' => 'field_65908956a5556',
                    'label' => 'Transaction Date',
                    'name' => 'transaction_date',
                    'aria-label' => '',
                    'type' => 'date_picker',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '15',
                        'class' => '',
                        'id' => '',
                    ),
                    'display_format' => 'm/d/Y',
                    'return_format' => 'Y-m-d',
                    'first_day' => 1,
                    'default_to_current_date' => 0,
                ),
                array(
                    'key' => 'field_659089f410c9f',
                    'label' => 'Amount',
                    'name' => 'amount', // TODO: rename as transaction_amount(?)
                    'aria-label' => '',
                    'type' => 'number',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '10',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'min' => '',
                    'max' => '',
                    'placeholder' => '',
                    'step' => '',
                    'prepend' => '',
                    'append' => '',
                ),
                array(
                    'key' => 'field_65908a842dcab',
                    'label' => 'Date Posted',
                    'name' => 'transaction_date_copy', // TODO: rename as transaction_date_posted(?)
                    'aria-label' => '',
                    'type' => 'date_picker',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '15',
                        'class' => '',
                        'id' => '',
                    ),
                    'display_format' => 'm/d/Y',
                    'return_format' => 'Y-m-d',
                    'first_day' => 1,
                    'default_to_current_date' => 0,
                ),
                array(
                    'key' => 'field_65babe90f801b',
                    'label' => 'Tax Year',
                    'name' => 'tax_year',
                    'aria-label' => '',
                    'type' => 'number',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '15',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => 2024,
                    'min' => '',
                    'max' => '',
                    'placeholder' => '',
                    'step' => '',
                    'prepend' => '',
                    'append' => '',
                ),
                array(
                    'key' => 'field_659088fe76f19',
                    'label' => 'Account',
                    'name' => 'account',
                    'aria-label' => '',
                    'type' => 'post_object',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => array(
                        array(
                            array(
                                'field' => 'field_660d521730656',
                                'operator' => '!=',
                                'value' => '1',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '20',
                        'class' => '',
                        'id' => '',
                    ),
                    'post_type' => array(
                        0 => 'account',
                    ),
                    'post_status' => '',
                    'taxonomy' => '',
                    'return_format' => 'object',
                    'multiple' => 0,
                    'allow_null' => 0,
                    'bidirectional' => 0,
                    'ui' => 1,
                    'bidirectional_target' => array(
                    ),
                ),
                array(
                    'key' => 'field_65baa7dd361dc',
                    'label' => 'Account TMP',
                    'name' => 'account_tmp', // TODO: rename as account_txt (?)
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => array(
                        array(
                            array(
                                'field' => 'field_660d521730656',
                                'operator' => '!=',
                                'value' => '1',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '20',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'maxlength' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                ),
                array(
                    'key' => 'field_660d52be86754',
                    'label' => '',
                    'name' => '',
                    'aria-label' => '',
                    'type' => 'message',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => array(
                        array(
                            array(
                                'field' => 'field_660d521730656',
                                'operator' => '==',
                                'value' => '1',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '40',
                        'class' => '',
                        'id' => '',
                    ),
                    'message' => '',
                    'new_lines' => 'wpautop',
                    'esc_html' => 0,
                ),
                array(
                    'key' => 'field_659089e210c9e',
                    'label' => 'Description',
                    'name' => 'description',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '20',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'maxlength' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                ),
                array(
                    'key' => 'field_65908a6787ddc',
                    'label' => 'Statement Description',
                    'name' => 'statement_description',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '20',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'maxlength' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                ),
                array(
                    'key' => 'field_bkkp_transactions_original_description',
                    'label' => 'Original Description',
                    'name' => 'original_description',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '20',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'maxlength' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                ),
                array(
                    'key' => 'field_65baa64e7817b',
                    'label' => 'Transaction Tags',
                    'name' => 'tags',
                    'aria-label' => '',
                    'type' => 'taxonomy',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '40',
                        'class' => '',
                        'id' => '',
                    ),
                    'taxonomy' => 'transaction_tag',
                    'add_term' => 1,
                    'save_terms' => 1,
                    'load_terms' => 0,
                    'return_format' => 'id',
                    'field_type' => 'multi_select',
                    'allow_null' => 0,
                    'bidirectional' => 0,
                    'multiple' => 0,
                    'bidirectional_target' => array(
                    ),
                ),
                array(
                    'key' => 'field_65baa62078179',
                    'label' => 'Transaction Type',
                    'name' => 'transaction_type',
                    'aria-label' => '',
                    'type' => 'select',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '15',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => array(
                        'unknown' => 'Unknown',
                        'debit' => 'Debit',
                        'credit' => 'Credit',
                    ),
                    'default_value' => 'unknown',
                    'return_format' => 'value',
                    'multiple' => 0,
                    'allow_null' => 0,
                    'ui' => 0,
                    'ajax' => 0,
                    'placeholder' => '',
                    'create_options' => 0,
                    'save_options' => 0,
                ),
                array(
                    'key' => 'field_65bab47e48b18',
                    'label' => 'Import UID',
                    'name' => 'uid',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '40',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'maxlength' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                ),
                array(
                    'key' => 'field_65ceb5cc9b8d0',
                    'label' => 'Data Source',
                    'name' => 'data_source',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '', // e.g. Mint; USAA
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '15',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'maxlength' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                ),
                array(
                    'key' => 'field_65f49e6d68d96',
                    'label' => 'Amount (signed)',
                    'name' => 'amount_signed', // originally: 'import_amount'
                    'aria-label' => '',
                    'type' => 'number',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '15',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'min' => '',
                    'max' => '',
                    'placeholder' => '',
                    'step' => '',
                    'prepend' => '',
                    'append' => '',
                ),
                array(
                    'key' => 'field_65cf9801f8064',
                    'label' => 'Transaction Status TMP',
                    'name' => 'transaction_status_tmp', // TODO: rename as transaction_status_txt (?)
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '15',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'maxlength' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                ),
                array(
                    'key' => 'field_65baa6447817a',
                    'label' => 'Category TMP',
                    'name' => 'category_tmp',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '15',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'maxlength' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                ),
                array(
                    'key' => 'field_65baa6a80a107',
                    'label' => 'Notes',
                    'name' => 'notes',
                    'aria-label' => '',
                    'type' => 'textarea',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'maxlength' => '',
                    'rows' => '',
                    'placeholder' => '',
                    'new_lines' => '',
                ),
                array(
                    'key' => 'field_65cbcd6bca53c',
                    'label' => 'Related Content',
                    'name' => 'transactions_related_content_tab',
                    'aria-label' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'placement' => 'top',
                    'endpoint' => 0,
                    'selected' => 0,
                ),
                array(
                    'key' => 'field_65cbcd9bca53e',
                    'label' => 'Related Group',
                    'name' => 'transactions_groups',
                    'aria-label' => '',
                    'type' => 'post_object',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '20',
                        'class' => '',
                        'id' => '',
                    ),
                    'post_type' => array(
                        0 => 'group',
                    ),
                    'post_status' => '',
                    'taxonomy' => '',
                    'return_format' => 'id',
                    'multiple' => 1,
                    'allow_null' => 0,
                    'allow_in_bindings' => 1,
                    'bidirectional' => 1,
                    'bidirectional_target' => array(
                        0 => 'field_6759eb2826ee6',
                    ),
                    'ui' => 1,
                ),
                array(
                    'key' => 'field_65cbcdc4ca53f',
                    'label' => 'Related Person',
                    'name' => 'transactions_people',
                    'aria-label' => '',
                    'type' => 'post_object',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '20',
                        'class' => '',
                        'id' => '',
                    ),
                    'post_type' => array(
                        0 => 'person',
                    ),
                    'post_status' => '',
                    'taxonomy' => '',
                    'return_format' => 'id',
                    'multiple' => 1,
                    'allow_null' => 0,
                    'bidirectional' => 1,
                    'bidirectional_target' => array(
                        0 => 'field_65e73424b2b39',
                    ),
                    'ui' => 1,
                ),
                array(
                    'key' => 'field_65e7317bbd9f6',
                    'label' => 'Related Paycheck',
                    'name' => 'transactions_paychecks',
                    'aria-label' => '',
                    'type' => 'post_object',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '20',
                        'class' => '',
                        'id' => '',
                    ),
                    'post_type' => array(
                        0 => 'paycheck',
                    ),
                    'post_status' => '',
                    'taxonomy' => '',
                    'return_format' => 'id',
                    'multiple' => 0,
                    'allow_null' => 0,
                    'bidirectional' => 1,
                    'bidirectional_target' => array(
                        0 => 'field_65e7311453eba',
                    ),
                    'ui' => 1,
                ),
                array(
                    'key' => 'field_bkkp_transactions_taxpayments',
                    'label' => 'Related Tax Payment',
                    'name' => 'transactions_taxpayments',
                    'aria-label' => '',
                    'type' => 'post_object',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '20',
                        'class' => '',
                        'id' => '',
                    ),
                    'post_type' => array(
                        0 => 'tax_payment',
                    ),
                    'post_status' => '',
                    'taxonomy' => '',
                    'return_format' => 'id',
                    'multiple' => 0,
                    'allow_null' => 0,
                    'bidirectional' => 1,
                    'bidirectional_target' => array(
                        0 => 'field_67fe5ee4a273e',
                    ),
                    'ui' => 1,
                ),
                array(
                    'key' => 'field_bkkp_transactions_related',
                    'label' => 'Related Transaction', // (s)?
                    'name' => 'related_transactions',
                    'aria-label' => '',
                    'type' => 'post_object',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '20',
                        'class' => '',
                        'id' => '',
                    ),
                    'post_type' => array(
                        0 => 'transaction',
                    ),
                    'post_status' => '',
                    'taxonomy' => '',
                    'return_format' => 'id',
                    'multiple' => 0,
                    'allow_null' => 0,
                    'bidirectional' => 1,
                    'bidirectional_target' => array(
                    ),
                    'ui' => 1,
                ),
                array(
                    'key' => 'field_65e90f1bb1a69',
                    'label' => 'Files',
                    'name' => 'files',
                    'aria-label' => '',
                    'type' => 'gallery',
                    'instructions' => 'e.g. check image',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '40',
                        'class' => '',
                        'id' => '',
                    ),
                    'return_format' => 'array',
                    'library' => 'all',
                    'min' => '',
                    'max' => '',
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => '',
                    'insert' => 'append',
                    'preview_size' => 'thumbnail',
                ),
                array(
                    'key' => 'field_65cfa984032f3',
                    'label' => 'X-check',
                    'name' => 'x-check',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'maxlength' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                ),
                /*
                [
                    'key'           => 'field_bkkp_employment_employer',
                    'name'          => 'bkkp_employment_employer',
                    'label'         => 'Employer',
                    'type'          => 'post_object',
                    'post_type'     => ['employer'],
                    'return_format' => 'id',
                ],
                [
                    'key' => 'field_bkkp_employment_employer_name',
                    'name' => 'bkkp_employment_employer_name',
                    'label' => 'Employer Name',
                    'type' => 'text',
                ],
                [
                    'key'   => 'field_bkkp_employment_employer_ein',
                    'name'  => 'bkkp_employment_employer_ein',
                    'label' => 'EIN',
                    'type'  => 'text',
                ],
                */
            ],
            'location' => [
                [
                    [
                        'param' => 'post_type',
                        'operator' => '==',
                        'value' => 'transaction',
                    ],
                ],
            ],
        ]);
    }
}
